const user=[{
    "id": 1,
    "first_name": "Annabela",
    "last_name": "McGannon",
    "email": "amcgannon0@vimeo.com",
    "gender": "Genderqueer"
  }, {
    "id": 2,
    "first_name": "Karlyn",
    "last_name": "De Bruijn",
    "email": "kdebruijn1@disqus.com",
    "gender": "Agender"
  }, {
    "id": 3,
    "first_name": "Seth",
    "last_name": "Long",
    "email": "slong2@msu.edu",
    "gender": "Non-binary"
  }, {
    "id": 4,
    "first_name": "Morganica",
    "last_name": "Napthine",
    "email": "mnapthine3@utexas.edu",
    "gender": "Agender"
  }, {
    "id": 5,
    "first_name": "Wandis",
    "last_name": "Aveyard",
    "email": "waveyard4@plala.or.jp",
    "gender": "Male"
  }, {
    "id": 6,
    "first_name": "Teena",
    "last_name": "O'Rourke",
    "email": "torourke5@timesonline.co.uk",
    "gender": "Agender"
  }, {
    "id": 7,
    "first_name": "Livvyy",
    "last_name": "Gallaway",
    "email": "lgallaway6@istockphoto.com",
    "gender": "Agender"
  }, {
    "id": 8,
    "first_name": "Robbyn",
    "last_name": "Doddemeade",
    "email": "rdoddemeade7@infoseek.co.jp",
    "gender": "Non-binary"
  }, {
    "id": 9,
    "first_name": "Odella",
    "last_name": "Angelo",
    "email": "oangelo8@yandex.ru",
    "gender": "Male"
  }, {
    "id": 10,
    "first_name": "Alexei",
    "last_name": "Mahomet",
    "email": "amahomet9@craigslist.org",
    "gender": "Genderfluid"
  }]


module.exports= user;